#pragma once

enum eVisibleArea
{
    AREA_MAIN_MAP = 0,
    AREA_HOTEL,
    AREA_MANSION,
    AREA_BANK,
    AREA_MALL,
    AREA_STRIP_CLUB,
    AREA_LAWYERS,
    AREA_COFFEE_SHOP,
    AREA_CONCERT_HALL,
    AREA_STUDIO,
    AREA_RIFLE_RANGE,
    AREA_BIKER_BAR,
    AREA_POLICE_STATION,
    AREA_EVERYWHERE,
    AREA_DIRT,
    AREA_BLOOD,
    AREA_OVALRING,
    AREA_MALIBU_CLUB,
    AREA_PRINT_WORKS,
    MAX_VISIBLE_AREAS
};
