#pragma once

#define MAX_RADAR_TRACES 175

enum eCoordBlipAppearance
{
    COORD_BLIP_APPEARANCE_NORMAL = 0,
    COORD_BLIP_APPEARANCE_FRIEND,
    COORD_BLIP_APPEARANCE_ENEMY
};

enum eBlipDisplay
{
    BLIP_DISPLAY_NEITHER = 0,
    BLIP_DISPLAY_MARKER_ONLY,
    BLIP_DISPLAY_BLIP_ONLY,
    BLIP_DISPLAY_BOTH
};

enum eBlipColour
{
    BLIP_COLOUR_RED = 0,
    BLIP_COLOUR_GREEN,
    BLIP_COLOUR_BLUE,
    BLIP_COLOUR_WHITE,
    BLIP_COLOUR_YELLOW,
    BLIP_COLOUR_REDCOPY,
    BLIP_COLOUR_BLUECOPY,
    BLIP_COLOUR_THREAT,
    BLIP_COLOUR_DESTINATION
};

enum eRadarSprite
{
    RADAR_SPRITE_NONE = 0,
    RADAR_SPRITE_COUNT = 64
};
