#pragma once

enum eWeatherType
{
    WEATHER_EXTRASUNNY_LA = 0,
    WEATHER_SUNNY_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_CLOUDY_LA,
    WEATHER_SUNNY_SF,
    WEATHER_EXTRASUNNY_SF,
    WEATHER_CLOUDY_SF,
    WEATHER_RAINY_SF,
    WEATHER_FOGGY_SF,
    WEATHER_SUNNY_VEGAS,
    WEATHER_EXTRASUNNY_VEGAS,
    WEATHER_CLOUDY_VEGAS,
    WEATHER_EXTRASUNNY_COUNTRYSIDE,
    WEATHER_SUNNY_COUNTRYSIDE,
    WEATHER_CLOUDY_COUNTRYSIDE,
    WEATHER_RAINY_COUNTRYSIDE,
    WEATHER_EXTRASUNNY_DESERT,
    WEATHER_SUNNY_DESERT,
    WEATHER_SANDSTORM_DESERT,
    WEATHER_UNDERWATER,
    WEATHER_EXTRACOLOURS_1,
    WEATHER_EXTRACOLOURS_2
};
